import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Blog Post',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 outline w-full min-h-screen   mx-auto">{children}
      
      </body>
    </html>
  )
}
