import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./navbar";
import Footer from "./footer";
import { CounterContextProvider } from "@/Context/Context";

export const metadata: Metadata = {
  title: "Blog Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body className="flex flex-col min-h-screen justify-end ">
        <div className="items-start mt-0 mb-auto">
          <Navbar />
        </div>
        <CounterContextProvider> 
           {children} </CounterContextProvider>
        <div className="items-end mb-0 mt-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
